# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dc60e8f1fa3f6963433e58d6c788830581e1d5600d1f519d68e4b30b98e9f1f7d786fbd5f16e28d3c0b125c5407f2c1440b42304f0cbb7465626901f072f907

test:
  secret_key_base: a59b533b0df3e7b22cab74dd2e3511bc8708eb016c696e24be3cafe9d48d798c0ae9df7ab986b9ffa302139ac18bcef621fe268897075873242e8eb33806e4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
